repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
  - repo: local
    hooks:
      - id: just-lint
        entry: just lint
        language: system
        pass_filenames: false
        always_run: true
      - id: just-unit
        entry: just unit
        language: system
        pass_filenames: false
        always_run: true
      - id: just-zizmor
        entry: just zizmor
        language: system
        pass_filenames: false
        always_run: true
      - id: just-command-ref
        entry: just command-ref
        language: system
        pass_filenames: false
        always_run: true
