name: Full functional tests

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  functional-full:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - '3.10'
          - '3.11'
          - '3.12'
          - '3.13'
          - '3.14'
    environment: personal-token
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39  # v8.2.0
      - name: Run functional tests
        env:
          UV_PYTHON: ${{ matrix.python-version }}
          GITHUB_TOKEN: ${{ secrets.DWILDING_GITHUB_TOKEN }}
        run: uvx --from rust-just@1.52.0 just functional
