name: Run using uvx

on:
  pull_request:
  push:
    branches:
      - main

permissions: {}

jobs:
  uvx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57  # v8.0.0
      - name: Run gimmegit
        run: |
          set -ex
          package_dir="$PWD"
          mkdir -p demo
          cd demo
          result="$(GIMMEGIT_FORCE_STDOUT=1 uvx --from "$package_dir" gimmegit --allow-nested -u canonical dwilding/jubilant my-feature)"
          grep --quiet -F 'Installing pre-commit hook' <<< "$result"
          grep --quiet -F 'Cloned repo:' <<< "$result"
          grep --quiet -F '/jubilant/dwilding-my-feature' <<< "$result"
          cd jubilant/dwilding-my-feature
          status="$(uvx --from "$package_dir" gimmegit)"
          grep --quiet -F 'jubilant   canonical:main   dwilding:my-feature' <<< "$status"
